name: Linux build

on:
  push:
    branches: [ main, develop, 1.* ]
    tags: 1.*
    
  pull_request:
    branches: [ main, develop, 1.* ]

  workworkflow_dispatch:
    

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        qt: ['6.2.4', '6.3.2', '6.4.3', '6.5.1']

    steps:
    - uses: actions/checkout@v2
      
    - name: Installing Qt framework
      uses: jurplel/install-qt-action@v3
      with:
        version: ${{ matrix.qt }}      

    - name: Running qmake
      run:  cd $GITHUB_WORKSPACE; qmake pgmodeler.pro -r PREFIX=$GITHUB_WORKSPACE/build CONFIG+=debug

    - name: Building pgModeler
      run: make -j6
     
    - name: Deploying pgModeler
      run: make install

    - name: Create release artifact
      run: |
        cd $GITHUB_WORKSPACE
        tar -czvf pgmodeler.tar.gz -C build/ .
      if: success()

    - name: Upload release artifact
      uses: actions/upload-artifact@v2
      with:
        name: pgmodeler
        path: pgmodeler.tar.gz
